[project]
name = "genai-fundametals"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Rajesh Venkatesan", email = "rajeshetl78456@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "langchain>=1.4.1",
    "langchain-community>=0.4.2",
    "langchain-experimental>=0.4.2",
    "langchain-openai>=1.6.2",
    "openai>=3.14.1",
]

[project.scripts]
genai-fundametals = "genai_fundametals:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
